name: Docker CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup-node
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm install eslint --save-dev
    - run: npm ci
    
    - name: Run lint
      run: npm run lint
    
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: sb003/docker-cicd-test:latest
